/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author limas
 */
public class home extends javax.swing.JFrame {
    int xx, xy;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        principal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        panelEditais = new javax.swing.JPanel();
        labelEditais = new javax.swing.JLabel();
        panelBolsistas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelProjetos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        leftSide = new javax.swing.JPanel();
        btnProjetos = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnEditais = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBolsista = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de Gerenciamento de Projetos do IFBA");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo menor.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("Gerencie e organize os projetos do IFBA com facilidade");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        jPanel5.add(panelHome, "telaHome");

        panelEditais.setBackground(new java.awt.Color(255, 255, 255));

        labelEditais.setForeground(new java.awt.Color(0, 0, 0));
        labelEditais.setText("Editais");

        javax.swing.GroupLayout panelEditaisLayout = new javax.swing.GroupLayout(panelEditais);
        panelEditais.setLayout(panelEditaisLayout);
        panelEditaisLayout.setHorizontalGroup(
            panelEditaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditaisLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelEditais)
                .addContainerGap(1076, Short.MAX_VALUE))
        );
        panelEditaisLayout.setVerticalGroup(
            panelEditaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditaisLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelEditais)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        jPanel5.add(panelEditais, "telaEditais");

        panelBolsistas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bolsistas");

        javax.swing.GroupLayout panelBolsistasLayout = new javax.swing.GroupLayout(panelBolsistas);
        panelBolsistas.setLayout(panelBolsistasLayout);
        panelBolsistasLayout.setHorizontalGroup(
            panelBolsistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBolsistasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addContainerGap(1058, Short.MAX_VALUE))
        );
        panelBolsistasLayout.setVerticalGroup(
            panelBolsistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBolsistasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(558, Short.MAX_VALUE))
        );

        jPanel5.add(panelBolsistas, "telaBolsistas");

        panelProjetos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Projetos");

        javax.swing.GroupLayout panelProjetosLayout = new javax.swing.GroupLayout(panelProjetos);
        panelProjetos.setLayout(panelProjetosLayout);
        panelProjetosLayout.setHorizontalGroup(
            panelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjetosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addContainerGap(1084, Short.MAX_VALUE))
        );
        panelProjetosLayout.setVerticalGroup(
            panelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjetosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        jPanel5.add(panelProjetos, "telaProjetos");

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 0, 1180, -1));

        leftSide.setBackground(new java.awt.Color(0, 153, 51));
        leftSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProjetos.setBackground(new java.awt.Color(204, 255, 204));
        btnProjetos.setForeground(new java.awt.Color(0, 0, 0));
        btnProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapis.png"))); // NOI18N
        btnProjetos.setText("Projetos");
        btnProjetos.setBorderPainted(false);
        btnProjetos.setOpaque(false);
        btnProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjetosActionPerformed(evt);
            }
        });
        leftSide.add(btnProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 40));

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorderPainted(false);
        btnHome.setOpaque(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        leftSide.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        btnEditais.setBackground(new java.awt.Color(204, 255, 204));
        btnEditais.setForeground(new java.awt.Color(0, 0, 0));
        btnEditais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book_icon_158035.png"))); // NOI18N
        btnEditais.setText("Editais");
        btnEditais.setBorderPainted(false);
        btnEditais.setOpaque(false);
        btnEditais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaisActionPerformed(evt);
            }
        });
        leftSide.add(btnEditais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SGPIF");
        leftSide.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 43));

        btnBolsista.setBackground(new java.awt.Color(204, 255, 204));
        btnBolsista.setForeground(new java.awt.Color(0, 0, 0));
        btnBolsista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnBolsista.setText("Bolsistas");
        btnBolsista.setBorderPainted(false);
        btnBolsista.setOpaque(false);
        btnBolsista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolsistaActionPerformed(evt);
            }
        });
        leftSide.add(btnBolsista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 40));

        getContentPane().add(leftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 773));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void btnProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjetosActionPerformed
        CardLayout cl = (CardLayout) jPanel5.getLayout();
        cl.show(jPanel5, "telaProjetos");
    }//GEN-LAST:event_btnProjetosActionPerformed

    private void btnEditaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaisActionPerformed
        CardLayout cl = (CardLayout) jPanel5.getLayout();
        cl.show(jPanel5, "telaEditais");
    }//GEN-LAST:event_btnEditaisActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        CardLayout cl = (CardLayout) jPanel5.getLayout();
        cl.show(jPanel5, "telaHome");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBolsistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolsistaActionPerformed
        CardLayout cl = (CardLayout) jPanel5.getLayout();
        cl.show(jPanel5, "telaBolsistas");
    }//GEN-LAST:event_btnBolsistaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(((x-xx)-230), y-xy);
        //System.out.println(((x-xx)-500) +" "+ (y-xy));
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
        //System.out.println(xx + " " + xy);
    }//GEN-LAST:event_jPanel1MousePressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBolsista;
    private javax.swing.JButton btnEditais;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProjetos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelEditais;
    private javax.swing.JPanel leftSide;
    private javax.swing.JPanel panelBolsistas;
    private javax.swing.JPanel panelEditais;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelProjetos;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
